// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.mms
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Request : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public MethodType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id", IsRequired = true)]
        public string RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(100)]
        public Ping ping { get; set; }

        [global::ProtoBuf.ProtoMember(101)]
        public IssueNodeId issue_node_id { get; set; }

        [global::ProtoBuf.ProtoMember(102)]
        public EntryMatching entry_matching { get; set; }

        [global::ProtoBuf.ProtoMember(103)]
        public CheckMatching check_matching { get; set; }

        [global::ProtoBuf.ProtoMember(104)]
        public CancelMatching cancel_matching { get; set; }

        [global::ProtoBuf.ProtoMember(200)]
        public MatchingSetting matching_setting { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Ping : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class IssueNodeId : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"pcb_serial", IsRequired = true)]
            public string PcbSerial { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"loc_id", IsRequired = true)]
            public string LocId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"issue_at", IsRequired = true)]
            public uint IssueAt { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"issue_count")]
            [global::System.ComponentModel.DefaultValue(1u)]
            public uint IssueCount
            {
                get => __pbn__IssueCount ?? 1u;
                set => __pbn__IssueCount = value;
            }
            public bool ShouldSerializeIssueCount() => __pbn__IssueCount != null;
            public void ResetIssueCount() => __pbn__IssueCount = null;
            private uint? __pbn__IssueCount;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EntryMatching : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"apply_id", IsRequired = true)]
            public uint ApplyId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"myclient", IsRequired = true)]
            public Client Myclient { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"myplayer", IsRequired = true)]
            public Player Myplayer { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"world")]
            public World World { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"groups")]
            public global::System.Collections.Generic.List<Group> Groups { get; } = new global::System.Collections.Generic.List<Group>();

            [global::ProtoBuf.ProtoMember(7, Name = @"matching_timeout", IsRequired = true)]
            public uint MatchingTimeout { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"seq_num")]
            public uint SeqNum
            {
                get => __pbn__SeqNum.GetValueOrDefault();
                set => __pbn__SeqNum = value;
            }
            public bool ShouldSerializeSeqNum() => __pbn__SeqNum != null;
            public void ResetSeqNum() => __pbn__SeqNum = null;
            private uint? __pbn__SeqNum;

            [global::ProtoBuf.ProtoMember(9, Name = @"create_room_flag")]
            [global::System.ComponentModel.DefaultValue(1u)]
            public uint CreateRoomFlag
            {
                get => __pbn__CreateRoomFlag ?? 1u;
                set => __pbn__CreateRoomFlag = value;
            }
            public bool ShouldSerializeCreateRoomFlag() => __pbn__CreateRoomFlag != null;
            public void ResetCreateRoomFlag() => __pbn__CreateRoomFlag = null;
            private uint? __pbn__CreateRoomFlag;

            [global::ProtoBuf.ProtoMember(10, Name = @"entry_at", IsRequired = true)]
            public uint EntryAt { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"bl_banapassport_am_ids")]
            public uint[] BlBanapassportAmIds { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"bl_loc_ids")]
            public global::System.Collections.Generic.List<string> BlLocIds { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoContract()]
            public partial class Group : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(2, Name = @"client", IsRequired = true)]
                public Client Client { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"player", IsRequired = true)]
                public Player Player { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CheckMatching : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"node_id", IsRequired = true)]
            public uint NodeId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"check_at", IsRequired = true)]
            public uint CheckAt { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CancelMatching : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"node_id", IsRequired = true)]
            public uint NodeId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"apply_id", IsRequired = true)]
            public uint ApplyId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"cancel_at", IsRequired = true)]
            public uint CancelAt { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MatchingSetting : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"user_id", IsRequired = true)]
            public uint UserId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"world", IsRequired = true)]
            public World World { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"conditions")]
            public global::System.Collections.Generic.List<Condition> Conditions { get; } = new global::System.Collections.Generic.List<Condition>();

            [global::ProtoBuf.ProtoContract()]
            public partial class Condition : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"attribute_id", IsRequired = true)]
                public uint AttributeId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
                public ParameterType Type { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"parameter", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
                public long Parameter { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"expr_id", IsRequired = true)]
                public Expression ExprId { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"relative", IsRequired = true)]
                public bool Relative { get; set; }

            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Response : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public MethodType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id", IsRequired = true)]
        public string RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"code", IsRequired = true)]
        public ErrorCode Code { get; set; } = ErrorCode.ErrServer;

        [global::ProtoBuf.ProtoMember(100)]
        public Ping ping { get; set; }

        [global::ProtoBuf.ProtoMember(101)]
        public IssueNodeId issue_node_id { get; set; }

        [global::ProtoBuf.ProtoMember(102)]
        public EntryMatching entry_matching { get; set; }

        [global::ProtoBuf.ProtoMember(103)]
        public CheckMatching check_matching { get; set; }

        [global::ProtoBuf.ProtoMember(104)]
        public CancelMatching cancel_matching { get; set; }

        [global::ProtoBuf.ProtoMember(200)]
        public MatchingSetting matching_setting { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Ping : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class IssueNodeId : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"node_id")]
            public uint[] NodeIds { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EntryMatching : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"poling_interval", IsRequired = true)]
            public uint PolingInterval { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"apply_id", IsRequired = true)]
            public uint ApplyId { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CheckMatching : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"room_id")]
            public uint RoomId
            {
                get => __pbn__RoomId.GetValueOrDefault();
                set => __pbn__RoomId = value;
            }
            public bool ShouldSerializeRoomId() => __pbn__RoomId != null;
            public void ResetRoomId() => __pbn__RoomId = null;
            private uint? __pbn__RoomId;

            [global::ProtoBuf.ProtoMember(2, Name = @"apply_id")]
            public uint ApplyId
            {
                get => __pbn__ApplyId.GetValueOrDefault();
                set => __pbn__ApplyId = value;
            }
            public bool ShouldSerializeApplyId() => __pbn__ApplyId != null;
            public void ResetApplyId() => __pbn__ApplyId = null;
            private uint? __pbn__ApplyId;

            [global::ProtoBuf.ProtoMember(3, Name = @"clients")]
            public global::System.Collections.Generic.List<MatchedClient> Clients { get; } = new global::System.Collections.Generic.List<MatchedClient>();

            [global::ProtoBuf.ProtoContract()]
            public partial class MatchedClient : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"group_id", IsRequired = true)]
                public uint GroupId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"client", IsRequired = true)]
                public Client Client { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CancelMatching : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MatchingSetting : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Client : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node_id", IsRequired = true)]
        public uint NodeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pcb_serial", IsRequired = true)]
        public string PcbSerial { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"loc_id", IsRequired = true)]
        public string LocId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"subnet_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SubnetId
        {
            get => __pbn__SubnetId ?? "";
            set => __pbn__SubnetId = value;
        }
        public bool ShouldSerializeSubnetId() => __pbn__SubnetId != null;
        public void ResetSubnetId() => __pbn__SubnetId = null;
        private string __pbn__SubnetId;

        [global::ProtoBuf.ProtoMember(5, Name = @"pref_code", IsRequired = true)]
        public uint PrefCode { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"global_ipaddress")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GlobalIpaddress
        {
            get => __pbn__GlobalIpaddress ?? "";
            set => __pbn__GlobalIpaddress = value;
        }
        public bool ShouldSerializeGlobalIpaddress() => __pbn__GlobalIpaddress != null;
        public void ResetGlobalIpaddress() => __pbn__GlobalIpaddress = null;
        private string __pbn__GlobalIpaddress;

        [global::ProtoBuf.ProtoMember(7, Name = @"global_port")]
        public uint GlobalPort
        {
            get => __pbn__GlobalPort.GetValueOrDefault();
            set => __pbn__GlobalPort = value;
        }
        public bool ShouldSerializeGlobalPort() => __pbn__GlobalPort != null;
        public void ResetGlobalPort() => __pbn__GlobalPort = null;
        private uint? __pbn__GlobalPort;

        [global::ProtoBuf.ProtoMember(8, Name = @"local_ipaddress")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocalIpaddress
        {
            get => __pbn__LocalIpaddress ?? "";
            set => __pbn__LocalIpaddress = value;
        }
        public bool ShouldSerializeLocalIpaddress() => __pbn__LocalIpaddress != null;
        public void ResetLocalIpaddress() => __pbn__LocalIpaddress = null;
        private string __pbn__LocalIpaddress;

        [global::ProtoBuf.ProtoMember(9, Name = @"local_port")]
        public uint LocalPort
        {
            get => __pbn__LocalPort.GetValueOrDefault();
            set => __pbn__LocalPort = value;
        }
        public bool ShouldSerializeLocalPort() => __pbn__LocalPort != null;
        public void ResetLocalPort() => __pbn__LocalPort = null;
        private uint? __pbn__LocalPort;

        [global::ProtoBuf.ProtoMember(100, Name = @"nat_mapping_type", IsRequired = true)]
        public NatMappingType NatMappingType { get; set; }

        [global::ProtoBuf.ProtoMember(101, Name = @"nat_filtering_type", IsRequired = true)]
        public NatFilteringType NatFilteringType { get; set; }

        [global::ProtoBuf.ProtoMember(102, Name = @"nat_allocation_policy")]
        [global::System.ComponentModel.DefaultValue(NatAllocationPolicy.NaNone)]
        public NatAllocationPolicy NatAllocationPolicy
        {
            get => __pbn__NatAllocationPolicy ?? NatAllocationPolicy.NaNone;
            set => __pbn__NatAllocationPolicy = value;
        }
        public bool ShouldSerializeNatAllocationPolicy() => __pbn__NatAllocationPolicy != null;
        public void ResetNatAllocationPolicy() => __pbn__NatAllocationPolicy = null;
        private NatAllocationPolicy? __pbn__NatAllocationPolicy;

        [global::ProtoBuf.ProtoMember(200, Name = @"property")]
        public global::System.Collections.Generic.List<Property> Properties { get; } = new global::System.Collections.Generic.List<Property>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Property : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"property_id", IsRequired = true)]
            public uint PropertyId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"property_value", IsRequired = true)]
            public string PropertyValue { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Player : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"banapassport_am_id", IsRequired = true)]
        public uint BanapassportAmId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"parameters")]
        public global::System.Collections.Generic.List<Parameter> Parameters { get; } = new global::System.Collections.Generic.List<Parameter>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Parameter : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"attribute_id", IsRequired = true)]
            public uint AttributeId { get; set; }

            [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public long parameter { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class World : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mucha_game_id", IsRequired = true)]
        public string MuchaGameId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"version", IsRequired = true)]
        public uint Version { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"world_id", IsRequired = true)]
        public uint WorldId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SystemConstant
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PROTOBUF_MESSAGE_REVISION")]
        ProtobufMessageRevision = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"PROCESS_WAIT_POLING_INTERVAL")]
        ProcessWaitPolingInterval = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MATCH_CANCELED")]
        MatchCanceled = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PROCESS_WAIT")]
        ProcessWait = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ERR_REQUEST")]
        ErrRequest = 100,
        [global::ProtoBuf.ProtoEnum(Name = @"ERR_SERVER")]
        ErrServer = 101,
        [global::ProtoBuf.ProtoEnum(Name = @"ERR_MAINTENANCE")]
        ErrMaintenance = 102,
        [global::ProtoBuf.ProtoEnum(Name = @"ERR_MATCH_NOENTRY")]
        ErrMatchNoentry = 103,
        [global::ProtoBuf.ProtoEnum(Name = @"ERR_NODEID")]
        ErrNodeid = 200,
        [global::ProtoBuf.ProtoEnum(Name = @"ERR_MATCH_CONDITION")]
        ErrMatchCondition = 201,
        [global::ProtoBuf.ProtoEnum(Name = @"ERR_DUPLICATE_ENTRY")]
        ErrDuplicateEntry = 202,
        [global::ProtoBuf.ProtoEnum(Name = @"ERR_UNDEFINED")]
        ErrUndefined = 999,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MethodType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PING")]
        Ping = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ISSUE_NODE_ID")]
        IssueNodeId = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTRY_MATCHING")]
        EntryMatching = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CHECK_MATCHING")]
        CheckMatching = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CANCEL_MATCHING")]
        CancelMatching = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"MATCHING_SETTING")]
        MatchingSetting = 100,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ParameterType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TYPE_NUMBER")]
        TypeNumber = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TYPE_FLAG")]
        TypeFlag = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Expression
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EXPR_EQ")]
        ExprEq = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPR_NE")]
        ExprNe = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPR_LT")]
        ExprLt = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPR_LE")]
        ExprLe = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPR_GT")]
        ExprGt = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPR_GE")]
        ExprGe = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPR_BW")]
        ExprBw = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LogicalOperator
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIC_AND")]
        LogicAnd = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIC_OR")]
        LogicOr = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Relative
    {
        [global::ProtoBuf.ProtoEnum(Name = @"RLT_ABSOLUTE")]
        RltAbsolute = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RLT_RELATIVE")]
        RltRelative = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum NatMappingType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NM_NONE")]
        NmNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NM_ENDPOINT_INDEPENDENT")]
        NmEndpointIndependent = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"NM_ADDRESS_DEPENDENT")]
        NmAddressDependent = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"NM_ADDRESS_AND_PORT_DEPENDENT")]
        NmAddressAndPortDependent = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum NatFilteringType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NF_NONE")]
        NfNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NF_ENDPOINT_INDEPENDENT")]
        NfEndpointIndependent = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"NF_ADDRESS_DEPENDENT")]
        NfAddressDependent = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"NF_ADDRESS_AND_PORT_DEPENDENT")]
        NfAddressAndPortDependent = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum NatAllocationPolicy
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NA_NONE")]
        NaNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NA_PORT_PRESERVATION")]
        NaPortPreservation = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"NA_PORT_CONTIGUITY")]
        NaPortContiguity = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"NA_RANDOM")]
        NaRandom = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
